### ISSUE TITLE
咪咕频道直播源没有维护啊，还是看不了。

### ISSUE THREAD

**Issue by maoyuyu** [Potato-66/SimpleTV#10]

**Comment by Potato-66** [comment]
更新到1.0.7版本

**Comment by maoyuyu** [comment]
> 更新到1.0.7版本就是更新了最新版，咪咕频道还是看不了

**Comment by maoyuyu** [comment]
> 更新到1.0.7版本就是更新最新版，咪咕频道还是看不了啊。

**Comment by Potato-66** [comment]
> > 更新到1.0.7版本就是更新最新版，咪咕频道还是看不了啊。

手动更新一下直播源

**Comment by maoyuyu** [comment]
> > > 更新到1.0.7版本就是更新最新版，咪咕频道还是看不了啊。
> 
> 手动更新一下直播源

就是手动更新了，咕咪所有频道也全是黑屏，是不是直播源的地址失效了，得换新的了。

**Comment by Potato-66** [comment]
> > > > 更新到1.0.7版本就是更新最新版，咪咕频道还是看不了啊。
> > 
> > 
> > 手动更新一下直播源
> 
> 就是手动更新了，咕咪所有频道也全是黑屏，是不是直播源的地址失效了，得换新的了。


https://github.com/user-attachments/assets/38426272-ec78-44a3-877a-a99ae87516f5

测试能正常播放，更新后咪咕只有32个频道
