### ISSUE TITLE
非常感谢您的创造，能开发一个可以自定义直播源的功能吗，感谢感谢

### ISSUE THREAD

**Issue by wolopo** [Potato-66/SimpleTV#12]
非常感谢您的创造，能开发一个可以自定义直播源的功能吗

这样就方便不同地区，和不同网络的网友使用，

再次感谢您的付出，！！！

**Comment by Potato-66** [comment]
> 非常感谢您的创造，能开发一个可以自定义直播源的功能吗
> 
> 
> 
> 这样就方便不同地区，和不同网络的网友使用，
> 
> 
> 
> 再次感谢您的付出，！！！

自定义直播源可以考虑使用TVBox或者Tivimate
