### ISSUE TITLE
怎么所有的频道都播放不到了

### ISSUE THREAD

**Issue by aitiou** [Potato-66/SimpleTV#2]
8号开始所有的频道都无法播放了

**Comment by Potato-66** [comment]
> 8号开始所有的频道都无法播放了

按菜单键进入设置，点击更新频道源，更新成功后切换频道

**Comment by Zickzeon2** [comment]
大佬，下载了1.0.4，打开后加载不了频道列表，也更新不了

**Comment by aitiou** [comment]
貌似所有的IPTV源又失效了

**Comment by Potato-66** [comment]
> 貌似所有的IPTV源又失效了

刚刚测试大部分频道都可正常播放
