### ISSUE TITLE
建议增加字体大小调节功能

### ISSUE THREAD

**Issue by kingstien** [Potato-66/SimpleTV#5]
目前的菜单字体大小老人离远点就看不太清了，建议增加字体大小调节功能，方便用户调节字体的大小。

**Comment by Potato-66** [comment]
> 目前的菜单字体大小老人离远点就看不太清了，建议增加字体大小调节功能，方便用户调节字体的大小。

可以，下个版本考虑加入

**Comment by Potato-66** [comment]
> 目前的菜单字体大小老人离远点就看不太清了，建议增加字体大小调节功能，方便用户调节字体的大小。

已支持，请下载安装最新版本
