### ISSUE TITLE
很棒！期待能增加自定义源功能！并支持Android4.4

### ISSUE THREAD

**Issue by 4yt1k** [Potato-66/SimpleTV#6]
内置直播源质量还是很高的，不过还是有个别频道卡顿或是不能播放，毕竟国内不同宽带运营商之间有隔离带啊。
开机直接进入电视直播，这个需求面向的群体以老人为主，还有部分是不愿意折腾的人。
那么问题来了，实现这个需求，是不是得把软件安装在机顶盒里面？机顶盒很多都是Android4.4的吧？

如果直接安装在电视里面，电视还是Android4.4的可能不多了，但电视也很少有能设置开机启动软件的吧？
也就是说，要点一下图标才启动应用进行电视直播的话，那能取代SimpleTV就多了，这种情况下至少我就更愿意用TVBox。

总结一下，我判断有开机直接进入电视直播需求的，对应设备是Android4.4的比例很高，所以SimpleTV很有必要支持该版本！

**Comment by meooxx** [comment]
> 1.关于自定义直播源功能。如你所说，如果有自定义需求的用户可以选择TVBox、dipy、TiViMate等空壳软件。创建这个项目的初衷是为了那些不会设置自定义源并且希望打开软件就能收看电视直播的用户的，所以不会考虑支持自定义直播源。个别频道卡顿无法播放问题，目前只能尽量去收集网络上可用的直播源，保证大部分央视和卫视能正常观看。 2.关于开机自启。目前确实大部分电视盒子以及智能电视都屏蔽了该权限，不过影响也不大，大部分用户找到应用入口还是没问题的。 3.关于最低版本。由于手上只有一个小米盒子是6.0的系统，所以暂时设置的最低版本为6.0，后续如果能找到4.4版本的模拟器或者电视盒子，会考虑支持。
> 
> > 内置直播源质量还是很高的，不过还是有个别频道卡顿或是不能播放，毕竟国内不同宽带运营商之间有隔离带啊。 开机直接进入电视直播，这个需求面向的群体以老人为主，还有部分是不愿意折腾的人。 那么问题来了，实现这个需求，是不是得把软件安装在机顶盒里面？机顶盒很多都是Android4.4的吧？
> > 如果直接安装在电视里面，电视还是Android4.4的可能不多了，但电视也很少有能设置开机启动软件的吧？ 也就是说，要点一下图标才启动应用进行电视直播的话，那能取代SimpleTV就多了，这种情况下至少我就更愿意用TVBox。
> > 总结一下，我判断有开机直接进入电视直播需求的，对应设备是Android4.4的比例很高，所以SimpleTV很有必要支持该版本！

内置源跟可定义源不冲突啊，加个自定义源路径，想搞的自己折腾呗。另外，大部分的iptv客户端不知道怎么回事，在小米电视上连不上网，真的无语了。另外推荐可靠优质源 [https://github.com/YueChan/Live](https://github.com/YueChan/Live)
而且更新最好变成，定时任务比如一天，一周，一月这样自动更新源地址
