### ISSUE TITLE
期待大佬的下一版app支持数字键切换频道的功能

### ISSUE THREAD

**Issue by bian-sdufe** [Potato-66/SimpleTV#8]
大佬，能不能增加遥控器数字键换台功能呀？家里的机顶盒只有老人用来看电视，他们用方向键换台挺麻烦，如果能支持数字键切换频道就好啦！感谢感谢呀~

**Comment by Potato-66** [comment]
> 大佬，能不能增加遥控器数字键换台功能呀？家里的机顶盒只有老人用来看电视，他们用方向键换台挺麻烦，如果能支持数字键切换频道就好啦！感谢感谢呀~

可以按确认+方向键快速选择频道呀，主要频道号也不是固定的，有些直播源失效了后期可能会删除掉
